/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import co.edu.unicartagena.persistencia.BD;
import javax.swing.JOptionPane;

/**
 *
 * @author j
 */
public class Principal extends javax.swing.JFrame {
static BD bd=new BD();

    public BD getBd() {
        return bd;
    }

    public void setBd(BD bd) {
        this.bd = bd;
    }


    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        maxPrecio = new javax.swing.JMenuItem();
        Iva = new javax.swing.JMenuItem();
        minCant = new javax.swing.JMenuItem();
        ProvMaxPrecio = new javax.swing.JMenuItem();
        borrar = new javax.swing.JMenuItem();
        agregarProducto = new javax.swing.JMenu();
        AgregarProducto = new javax.swing.JMenuItem();
        agregarInventario = new javax.swing.JMenuItem();
        agregarProveedor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("listar");

        maxPrecio.setText("Maximo precio");
        maxPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxPrecioActionPerformed(evt);
            }
        });
        jMenu1.add(maxPrecio);

        Iva.setText("Aumentar iva");
        Iva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IvaActionPerformed(evt);
            }
        });
        jMenu1.add(Iva);

        minCant.setText("Minima cantidad");
        minCant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minCantActionPerformed(evt);
            }
        });
        jMenu1.add(minCant);

        ProvMaxPrecio.setText("Proveedor con maximo precio");
        ProvMaxPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProvMaxPrecioActionPerformed(evt);
            }
        });
        jMenu1.add(ProvMaxPrecio);

        borrar.setText("Borrar ");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });
        jMenu1.add(borrar);

        jMenuBar1.add(jMenu1);

        agregarProducto.setText("agregar");
        agregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarProductoActionPerformed(evt);
            }
        });

        AgregarProducto.setText("Agregar producto");
        AgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarProductoActionPerformed(evt);
            }
        });
        agregarProducto.add(AgregarProducto);

        agregarInventario.setText("Agregar inventario");
        agregarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarInventarioActionPerformed(evt);
            }
        });
        agregarProducto.add(agregarInventario);

        agregarProveedor.setText("Agregar proveedor");
        agregarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarProveedorActionPerformed(evt);
            }
        });
        agregarProducto.add(agregarProveedor);

        jMenuBar1.add(agregarProducto);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarInventarioActionPerformed
        jScrollPane1.getViewport().add(new AgregarInventario());
    }//GEN-LAST:event_agregarInventarioActionPerformed

    private void maxPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxPrecioActionPerformed
        JOptionPane.showMessageDialog(null, bd.mayor()+"");
    }//GEN-LAST:event_maxPrecioActionPerformed

    private void IvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IvaActionPerformed
        JOptionPane.showMessageDialog(null, bd.subirIVA());
    }//GEN-LAST:event_IvaActionPerformed

    private void minCantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minCantActionPerformed
        JOptionPane.showMessageDialog(null, bd.minimaCantidad()+"");
    }//GEN-LAST:event_minCantActionPerformed

    private void ProvMaxPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProvMaxPrecioActionPerformed
        JOptionPane.showMessageDialog(null, bd.ListarProveedoresMAX());
    }//GEN-LAST:event_ProvMaxPrecioActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        JOptionPane.showMessageDialog(null, bd.borrarInventario());
    }//GEN-LAST:event_borrarActionPerformed

    private void agregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarProductoActionPerformed
        jScrollPane1.getViewport().add(new AgregarProducto());
    }//GEN-LAST:event_agregarProductoActionPerformed

    private void agregarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarProveedorActionPerformed
        jScrollPane1.getViewport().add(new AgregarProveedor());
    }//GEN-LAST:event_agregarProveedorActionPerformed

    private void AgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarProductoActionPerformed
        jScrollPane1.getViewport().add(new AgregarProducto());
    }//GEN-LAST:event_AgregarProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AgregarProducto;
    private javax.swing.JMenuItem Iva;
    private javax.swing.JMenuItem ProvMaxPrecio;
    private javax.swing.JMenuItem agregarInventario;
    private javax.swing.JMenu agregarProducto;
    private javax.swing.JMenuItem agregarProveedor;
    private javax.swing.JMenuItem borrar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem maxPrecio;
    private javax.swing.JMenuItem minCant;
    // End of variables declaration//GEN-END:variables
}
